---
name: Build, Push & Deploy Dev 
on:
    push:
    branches: [main]

jobs:
    build-and-push:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
        uses: actions/checkout@v2

    - name: Set up Python
        uses: actions/setup-python@v1
        with:
        python-version: "3.8"

    - name: Install Dependencies
        run: |
        docker build -t test_image:latest .